### ISSUE TITLE
SteamVR driver discord server

### ISSUE THREAD

**Issue by hshakula** [peroht/osvr-additions#1]
@peroht, that's a pretty interesting way to contact you, but it's the easiest one.
I saw your comment here https://github.com/ValveSoftware/openvr/issues/1047#issuecomment-574728968, is the server referenced in this comment is still up? If yes, could you please share the live link? The one from the comment is not working anymore. Thank you in advance

**Comment by peroht** [comment]
Try this @hshakula https://discord.gg/rRjtpaxJ

**Comment by hshakula** [comment]
Thank you!
